apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-springboot
spec:
  template:
    spec:
      containers:
        - image: codepocuser/knative-springboot:latest
          ports:
            - containerPort: 8080