apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-springboot-native
  namespace: to-billy-dev
spec:
  template:
    spec:
      containers:
        - name: knative-springboot-native
          image: codepocuser/knative-springboot-native:latest #test
          ports:
            - containerPort: 8080
