apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-springboot-native
spec:
  template:
    spec:
      containers:
        - name: knative-springboot-native
          image: codepocuser/knative-springboot-native:latest
          ports:
            - containerPort: 8080