# Use Alpine Linux as the base image
FROM alpine:latest

# Install dependencies, if any, using Alpine's package manager
RUN apk add --no-cache libstdc++

# Add your application's user and group
RUN addgroup -S spring && adduser -S spring -G spring

# Copy the native executable to the container
COPY --chown=spring:spring build/native/nativeCompile/springboot /app
RUN chmod +x /app

# Use the spring user
USER spring

# Set the binary as the entrypoint of the container
ENTRYPOINT ["/app"]