apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-python
spec:
  template:
    spec:
      containers:
        - name: knative-python
          image: codepocuser/knative-python:latest
          ports:
            - containerPort: 8080