apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-nodejs
spec:
  template:
    spec:
      containers:
        - name: knative-nodejs
          image: codepocuser/knative-nodejs:latest
          ports:
            - containerPort: 8080