name: Node.js CI/CD

on:
  push:
    branches: 
      - master
    # paths:
    #   - 'nodejs/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./nodejs
        file: ./nodejs/Dockerfile
        push: true
        tags: codepocuser/knative-nodejs:latest

    - name: Deploy to OpenShift
      run: |
        echo ${{ secrets.OPENSHIFT_TOKEN }} | oc login ${{ secrets.OPENSHIFT_SERVER }} --token=${{ secrets.OPENSHIFT_TOKEN }} --insecure-skip-tls-verify
        oc apply -f ../../nodejs/deploy.yaml