name: SpringBoot Native Image CI/CD

on:
  push:
    branches:
      - master
#    paths:
#      - 'springboot/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set up GraalVM with Java 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'

      - name: Make gradlew executable
        run: chmod +x springboot/gradlew

      - name: Build native image with Gradle
        run: |
          cd springboot
          ./gradlew nativeBuild

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Docker native image
        uses: docker/build-push-action@v2
        with:
          context: ./springboot
          file: ./springboot/Dockerfile.native
          push: true
          tags: codepocuser/knative-springboot-native:latest

      - name: Deploy to OpenShift
        run: |
          echo ${{ secrets.OPENSHIFT_TOKEN }} | oc login ${{ secrets.OPENSHIFT_SERVER }} --token=${{ secrets.OPENSHIFT_TOKEN }} --insecure-skip-tls-verify
          oc apply -f springboot/deploy-native.yaml